spring:
  application:
    name: gdje-izlazimo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gdje_izlazimo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/gdje-izlazimo}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:false}

app:
  mail:
    from: ${APP_MAIL_FROM:noreply@gdje-izlazimo.local}

server:
  port: ${PORT:8081}

logging:
  level:
    org:
      hibernate:
        SQL: ${LOGGING_HIBERNATE_SQL:WARN}
        orm:
          jdbc:
            bind: ${LOGGING_HIBERNATE_BIND:WARN}
      springframework:
        web: ${LOGGING_SPRING_WEB:INFO}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:gdje-izlazimo}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:spring-admin-client}
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}

imagekit:
  public-key: ${IMAGEKIT_PUBLIC_KEY:}
  private-key: ${IMAGEKIT_PRIVATE_KEY:}
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT:}

gemini:
  api-key: ${GEMINI_API_KEY:}
  model: ${GEMINI_MODEL:}

springdoc:
  api-docs:
    path: /v3/api-docs
  scalar:
    path: /scalar